import { OptionsModel } from './options.model';
import { RowsModel } from './rows.model';
import { ColorsModel } from './colors.model';
import { SelectionModel } from './selection.model';
import { IconsModel } from './icons.model';
import { SequenceInfoModel } from './sequenceInfoModel';
import { EventsModel } from './events.model';
import { PatternsModel } from './patterns.model';
import { InputModel } from './input.model';
import { ConsensusModel } from './consensus.model';
export declare class SequenceViewer {
    static sqvList: any[];
    divId: string;
    init: boolean;
    input: InputModel;
    params: OptionsModel;
    rows: RowsModel;
    consensus: ConsensusModel;
    regions: ColorsModel;
    patterns: PatternsModel;
    icons: IconsModel;
    labels: SequenceInfoModel;
    selection: SelectionModel;
    events: EventsModel;
    constructor(divId?: string);
    drawSequenceViewer(input1?: any, input2?: any, input3?: any, input4?: any, input5?: any, input6?: any, input7?: any): void;
    private generateLabels(idx, labels, startIndexes, topIndexes, chunkSize, fontSize, tooltips, data);
    private addTopIndexes(topIndexes, chunkSize, x, maxTop);
    private createGUI(data, labels, startIndexes, tooltips, options);
}
